language: ruby
rvm:
  - 2.1


before_script:
 - chmod +x ./_script/cibuild # or do this locally and commit
 - bundle update

script:
  - ./_script/cibuild

bundler_args: --without benchmark:site:development

cache: bundler

sudo: false

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
  email:
    recipients:
      - consultoria@carlosdelfino.eti.br

# branch whitelist
branches:
  only:
  - master
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"
