language: ruby

rvm:
- 2.1

script: jekyll build --safe --trace

# branch whitelist
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
