before_script: bundle update
bundler_args: --without benchmark:site:development
cache: bundler
language: ruby
sudo: false
before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

rvm:
  - &ruby1 2.3.0
  - &ruby2 2.2.4
  - &ruby3 2.1.8
  - &ruby4 2.0.0-p648
  - &jruby jruby-9.0.4.0
  - &rhead ruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: *jruby
    - rvm: *rhead
env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber

notifications:
  irc:
    template: "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
    channels: irc.freenode.org#jekyll

  email:
    recipients:
      - jordon@envygeeks.io


# branch whitelist, only for GitHub Pages
branches:
  only:
  

# branch whitelist
branches:
  only:
  - master
#  - gh-pages     # test the gh-pages branch
#  - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
