atom:
  buildCommand:
    - /usr/local/bin/bundle
    - exec
    - jekyll
    - serve
    - --incremental
    - --drafts
    - --safe
    - --open-url
    - --whatch
    - --future
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _posts
    - _drafts
  defaultPostDir: _drafts

# Ativa depuração no site, desde que no localhost
debug: false

# Site settings
title: Carlos Delfino
subtitle: "Microcontroladores e Mobile"
description: "Cursos e Desenvolvimento para dispositivos moveis multiplataforma, microcontroladores AVR (ATmega e ATtiny) e  ARM (Família Cortex-M), entre outros."
keywords: nrf, nrf51, nrf52, nrf5x, NativeScript, Multiplataforma, dispositivos moveis, celulares, SmartTV, Redes, Consultoria, TIC, Arduino, AVR, ATMega, ATMel, ARM, SAM4S, xPlained, C/C++, Java, Android, Automação, Aulas, Tutoria, Cursos, EAD, Treinamento, Instrumentação de Projetos, Social, Voluntáriado, Reflexões, Contos, História de Vida, Aprendizado, EAD, E-Learning, Moodle, AVA, CVA, CMS, Joomla, Aprendizado, Ensino a Distância
locale: pt_BR
charset: utf-8
encoding: utf-8
# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
teaser: carlosdelfino-palestra-400x161.png
cover: carlosdelfino-palestra.png
logo: logo-fullservice-120x120.png

ads: true

excerpt_separator: <!--more-->

uservoice:
   accentcolor: '#448dd6'
   triggercolor: 'white'
   triggerbackgroundcolor: 'rgba(46, 49, 51, 0.6)'
   enableall: false

linkedin:
   api: "78s8yjpx4xhlmj"
   TokenOAuth: "5cfbf5d6-8924-490b-860e-6da465590801"
   authorize: true

disqus:
   shortname: carlosdelfino

google:
   analytics:
      id: UA-21710445-1
      domain:
   adsense:
      client: ca-pub-1710447158146560
      slot: 8511319937

flattr:
   id: fbzv3r5
   login: CarlosDelfino

facebook:
  appid: 351518334888083
  uselogin: false
  scope: [user_friends, email]
  wellcomemsg: "Olá "

testimonial:
  itens: 6
  truncate: 350

# Exibe o mosquito aedes aegypti, campanha contra o mosquito
aedes:
  show: false

sass:
   sass_dir: _sass
   style: compressed

permalink: /:categories/:title/


keep_files:
  - "CNAME"

# Build settings
markdown: kramdown
highlighter: rouge

gems:
 - jekyll-feed
 - jekyll-gist
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-mentions
 - jekyll-coffeescript
 - jekyll-redirect-from
 - jekyll-sass-converter
 - jekyll-redirect-from
 - jekyll-seo-tag
 - kramdown
 - liquid
 - rouge
 - pygments
 - jemoji
 - sass
 - safe_yaml

# Site owner
owner:
   name: Carlos Delfino
   email: consultoria@carlosdelfino.eti.br
   twitter: fullsrv
   bio: Desenvolvedor e consultor para projetos com Microcontroladores e Mobile
   avatar: carlosdelfino.png
   google:
      plus: +CarlosDelfinoCarvalhoPinheiro

compress_html:
  enable: false
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  blanklines: true
  profile: true
  only_local_profile: true

resolvermaps:
  enable: true
  size: 201
  font: arial
  id: 0bwpn194rsa

exclude:
  - "/suporte-geral/"
  - "/script/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"
  - "vendor"
  - "lib"
  - "config.rb"
  - ".sass-cache"
  - "Capfile"
  - "config"
  - "log"
  - "Rakefile"
  - "Rakefile.rb"
  - "tmp"
  - "_tmp"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "_backup*"
  - "*.bck"
  - "*.tmp"
  - "/*.bck/"
  - "/*.tmp/"
  - ".git"
  - ".git*"
