# Site wide configuration

title: Carlos Delfino
description: "Consultoria e Serviços em TIC, Micro Controladores AVR, ARM e Prototipagem com Arduino"
keywords: Consultoria, TIC, Arduino, AVR, ATMega, ATMel, Arduino, ARM, SAM4S, xPlained, C/C++, Java, Android, Automação, Aulas, Cursos, EAD, Treinamento, Cursos
logo: logo-fullservice-120x120.png
teaser: carlosdelfino-palestra-400x161.png
locale: Belo Horizonte/MG, Brasil
url: http://carlosdelfino.eti.br
ads: true

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Carlos Delfino
  email: consultoria@carlosdelfino.eti.br
  twitter: fullsrv
  google:
    ad-client: ca-pub-1710447158146560 
    ad-slot: 8511319937
  bio: Analista de Suporte em Redes Windows e Linux, Analista de Desenvolvimento Java, PHP e C/C++ para Microcontroladores, Consultor, mais de 20 anos de experiência no mercado de TICs
  avatar: logo-fullservice-160x160.png 
disqus-shortname: carlosdelfino


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
