
# Site wide configuration

# Ativa depuração no site, desde que no localhost
debug: false

safe: true
lsi: false

title: Carlos Delfino
description: "Consultoria e Serviços em TICs, Desenvolvimento em diversas linguagens com Microcontroladores AVR, ARM e Prototipagem com Arduino"
keywords: Consultoria, TIC, Arduino, AVR, ATMega, ATMel, ARM, SAM4S, xPlained, C/C++, Java, Android, Automação, Aulas, Tutoria, Cursos, EAD, Treinamento, Instrumentação de Projetos, Social, Voluntáriado, Reflexões, Contos, História de Vida, Aprendizado, EAD, E-Learning, Moodle, AVA, CVA, CMS, Joomla, Aprendizado, Ensino a Distância
logo: logo-fullservice-120x120.png
teaser: carlosdelfino-palestra-400x161.png
locale: pt_BR
charset: utf-8
#url: http://localhost:4000
url: http://carlosdelfino.eti.br
#url: http://carlosdelfino.github.io/

ads: true 

excerpt_separator: <!--more-->

uservoice:
   accentcolor: '#448dd6'
   triggercolor: 'white'
   triggerbackgroundcolor: 'rgba(46, 49, 51, 0.6)'
   enableall: false

linkedin:
   api: "78s8yjpx4xhlmj"
   TokenOAuth: "5cfbf5d6-8924-490b-860e-6da465590801"
   authorize: true
   
disqus:
   shortname: carlosdelfino

google:
   analytics:
      id: UA-21710445-1
      domain:
   adsense:
      client: ca-pub-1710447158146560
      slot: 8511319937

flattr:
   id: fbzv3r5
   login: CarlosDelfino 

facebook:
  appid: 351518334888083
  uselogin: false
  scope: [user_friends, email]
  wellcomemsg: "Olá "
  
# Exibe o mosquito aedes aegypti, campanha contra o mosquito
aedes:
  show: false

# Jekyll configuration

sass:
   sass_dir: _sass
   style: compressed

permalink: /:categories/:title/

markdown: kramdown
highlighter: rouge

gems:
 - jekyll-feed	
 - jekyll-gist	
 - jekyll-paginate	
 - jekyll-sitemap
 - jekyll-mentions
 - jekyll-coffeescript
 - jekyll-redirect-from
 - jekyll-sass-converter
 - jekyll-textile-converter	
 - jekyll-redirect-from	
 - jekyll-seo-tag	
 - kramdown	
 - rdiscount	
 - redcarpet	
 - RedCloth	
 - liquid	
 - rouge	
 - jemoji	
 - html-pipeline	
 - sass	
 - safe_yaml

# Site owner
owner:
   name: Carlos Delfino
   email: consultoria@carlosdelfino.eti.br
   twitter: fullsrv
   bio: Analista de Redes Windows e Linux, Analista de Desenvolvimento em diversas linguagens, incluindo para Microcontroladores, Consultor, mais de 20 anos de experiência no mercado de TICs
   avatar: carlosdelfino.png
   google:
      plus: +CarlosDelfinoCarvalhoPinheiro

compress_html:
  enable: true
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
  blanklines: true
  profile: true
  only_local_profile: true

resolvermaps:
  enable:true
  size: 201
  font: arial
  id: 0bwpn194rsa

exclude: ["vendor", "lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", _backup]
