- type: steam
  title: Desenvolvimento de Firmware
  description: Desenvolvimento de firmware com a Arquitetura ARM (Família Cortex-M) AVR (Família ATMega e ATTiny) 
  link: /servicos/desenvolvimento_de_software

- type: monitor
  title: Desenvolvimento de Software
  description: Desenvolvimento de aplicações e softwares especializados com fins técnicos e analise de dados 

- type: wand
  title: Start Up
  description: Consultoria e Apoio tecnológico para Startups e Empresas Junior.

- type: edit
  title: Tutoriais e Apostilas
  description: Escrita de tutoriais e apostilas para cursos ténicos e treinamentos rápidos ligados a Tecnologia da Informação
  
- type: earth
  title: Traduções
  description: Traduções de manuais e apostilas para o Português.
  
- type: planet
  title: Infraestrutra de rede
  description: Infraestrutura de rede com microservers, servidores de arquivos, microsites e outros sistemas especiais de servidores.

- type: image
  title: Hospedagem
  description: Hospedagem de sites especiais, Moodle entre outros.
