- type: book
  title: Cursos
  description: Cursos com turmas abertas e fechadas, Basicão da Eletrônica, Arduino (Hello World Arduino, Hello World ARM), Mobile (NativeScript), Automação, Segurança integrada. Apostilas e tutoriais sobre encomenda.
  link: http://arduinominas.com.br

- type: laptop
  title: Desenvolvimento de Software
  description: Desenvolvimento de aplicações e softwares especializados com fins técnicos e analise de dados 

- type: business
  title: Start Up
  description: Consultoria e Apoio tecnológico para Startups e Empresas Junior.
  
- type: git-network
  title: Infraestrutra de rede
  description: Infraestrutura de rede com microservers, servidores de arquivos, microsites e outros sistemas especiais de servidores.

- type: desktop
  title: Hospedagem
  description: Hospedagem de sites especiais, Google Cloud, Firebase e sites para EAD como Moodle, entre outros.
