- type: book
  title: Cursos
  description: Cursos abertos e turmas fechadas, Basicão da Eletrônica, Arduino (HelloWorldArduino), Mobile (NativeScript), Automação, CFTV e Cercas Eletricas integradas.
  link: http://arduinominas.com.br

- type: logo-steam
  title: Desenvolvimento de Firmware
  description: Desenvolvimento de firmware com a Arquitetura ARM (Família Cortex-M) AVR (Família ATMega e ATTiny) 
  link: /servicos/desenvolvimento_de_software

- type: laptop
  title: Desenvolvimento de Software
  description: Desenvolvimento de aplicações e softwares especializados com fins técnicos e analise de dados 

- type: business
  title: Start Up
  description: Consultoria e Apoio tecnológico para Startups e Empresas Junior.

- type: bookmarks
  title: Tutoriais e Apostilas
  description: Escrita de tutoriais e apostilas para cursos ténicos e treinamentos rápidos ligados a Tecnologia da Informação
  link: /servicos/tutoriais
  
- type: flag
  title: Traduções
  description: Traduções de manuais e apostilas para o Português.
  
- type: git-network
  title: Infraestrutra de rede
  description: Infraestrutura de rede com microservers, servidores de arquivos, microsites e outros sistemas especiais de servidores.

- type: desktop
  title: Hospedagem
  description: Hospedagem de sites especiais, Moodle entre outros.
